### ISSUE TITLE
Scrollbar inception makes the interface hard to use

### ISSUE THREAD

**Issue by daniel-sch** [vivekratnavel/omniboard#110]
The size of the main table seems to be set slightly too big, so that the browser scrollbars are visible in addition to the scrollbars from react (that's where I think the inner scrollbars are from). This means that the inner scrollbars (that are needed to scroll the table) are only visible after scrolling the browser scrollbars to the bottom and right. Additionally, the mouse wheel doesn't work properly, especially if multiple rows are expanded.

You can see the problem in this screenshot:
![scrollbar_inception](https://user-images.githubusercontent.com/360180/58260546-f0bc5c80-7d76-11e9-8257-cd13294642fa.png)

I'm on Windows 10 and this happens with Firefox 67.0 and Chrome 74 (I didn't check other browsers).

Please let me know if I can be of any help in diagnosing this issue.
Thanks in advance

**Comment by avalcarce** [comment]
Both of these problems also happen to me on Windows 7 and Chrome 74.

**Comment by AustinT** [comment]
I also have this problem on mac OSX, Firefox. Seems like it should be an easy fix, but I don't know anything about web development so I don't know how I would change it.

**Comment by rmclarke** [comment]
Am also not really familiar with web development, but I've been digging around and I think I might have worked out why the native vertical scrollbar appears.

As far as I can tell, this method in `web/src/components/RunsTable/runsTable.js` determines the main table's height by subtracting its vertical position from the total height available:
```
  resizeTable = () => {
    const {tableWidth, tableHeight} = this.state;
    // Set the table width and height to occupy full viewport
    this.setState({
      tableWidth: window.innerWidth ? window.innerWidth : tableWidth,
      tableHeight: window.innerHeight && this.tableWrapperDomNode ? window.innerHeight - this.tableWrapperDomNode.offsetTop : tableHeight
    });
  };
```

However, the Auto-Refresh line (a div with the style class `status-bar`) just above the table is styled with `float: right!important`. For me (Ubuntu 16.04, Chrome 76), that causes it to overlap with the main `table-wrapper` div, rather than sitting above it. This presumably means `table-wrapper` thinks its vertical position is at the top of `status-bar`, rather than the bottom, so the table is too tall by exactly the height of the `status-bar`.

On my browser, I can fix this by removing the `pull-right` class from `status-bar` (which removes the float), then adding `text-align: right;` to restore the alignment. That removes the vertical scroll bar unless the window is narrower than 630px, so presumably something else is overflowing at that point.

I only got the extra horizontal scrollbar after resizing, and it would go away with a refresh. This change makes it not appear for me unless the window is narrower than 630px.

So possibly the bulk of this issue might be fixed by removing `.pull-right` from the Auto-Refresh status bar div, and adding `text-align: right;` to the `.status-bar` style class?

**Comment by vivekratnavel** [comment]
@rmclarke is right. I just tried Omniboard v2.1.0 in Firefox 69.0 in Mac OS and I did not face any issues with the scrollbar.

**Comment by daniel-sch** [comment]
Thanks, v2.1.0 does indeed solve the problem.
