### ISSUE TITLE
Feature request: more informative legend when comparing metric plots

### ISSUE THREAD

**Issue by sadaharu-inugami** [vivekratnavel/omniboard#180]
First and foremost, I'd like to thank you for your work on the amazing tool that Omniboard surely is.

I've got one small suggestion for data presentation when comparing different experiments. Currently, when comparing metric plots of different experiments, the legend entries are formatted as follows {run_id}.{metric_name}. By default, the run IDs saved by Sacred's MongoObserver are integers, which are not very informative at all. When comparing many experiments (let's say, 20), it is difficult to keep track of the IDs and remember which experiment is which. Experiment names instead of IDs could be a better choice here.

Fortunately, it is possible to create a custom Observer in Sacred and make it set the run ID manually as long as it is the observer with the highest priority and gets to set the ID. I've tried doing it but, apparently, Omniboard needs these run IDs to be numbers and no strings are allowed. Either changing the metric comparison legend entries or allowing non-numeric IDs would make Omniboard better suited for large experiment sets.

**Comment by vivekratnavel** [comment]
Added a dropdown to choose between "Run Id" and "Experiment Name" for Metric Label.

<img width="611" alt="Screen Shot 2020-03-01 at 1 22 02 AM" src="https://user-images.githubusercontent.com/1051198/75623191-8386f480-5b5c-11ea-833a-280c2b3cba02.png">

**Comment by MaxSchambach** [comment]
I am facing a similar issue. Adding the experiment name does not work for my workflow.I use the Experiment Name to group single runs with a common experiment target. Then, when comparing many runs, the ID is not very informative (as mentioned above) and the Experiment Name is not necessarily unique.

What I would suggest is to make it possible to add arbitrary (possibly multiple, concatenated) configuration parameters to the label.
This would make it very straightforward to compare different configuration hyperparameters, such as different model topologies, used optimizers, batch sizes (in case of ML) and so. For me, this would be a huge improvement when evaluating experiments with Omniboard! (Otherwise, I am, too, really enjoying working with Omniboard, very useful tool!)
