### ISSUE TITLE
Feature request: export table as csv

### ISSUE THREAD

**Issue by diegombar** [vivekratnavel/omniboard#196]
It would be nice if we could export the main omniboard table of experiments as a CSV file, so that we can use a spreadsheet to generate custom plots. Ideally, it would only include visible columns: metrics columns, custom columns, no "hidden" columns.

**Comment by MaxSchambach** [comment]
I thought about this as well. The conclusion that I came to is that working with the MongoDB database directly, rather then exporting raw data from Omniboard, should be the preferred way, as all the information is already saved there and high level data aggregation can be directly performed.
Hence, using for example [PyMongo](https://github.com/mongodb/mongo-python-driver) with a plot tool of your choice, is the preferred way in my point of view.

**Comment by vivekratnavel** [comment]
I agree with @MaxSchambach. Omniboard is only a tool to visualize sacred data from MongoDB. There are several tools available to get raw data from mongodb like the one @MaxSchambach mentioned. Closing this issue now. Thanks @MaxSchambach !

**Comment by diegombar** [comment]
Thanks for the reply. I thought it could benefit from interactive experiment and column filtering to quickly specify what we want to export, keeping Omniboard as the main interface to Sacred data. It would also be appealing for a larger user base, who may not be familiar with MongoDB.

**Comment by MaxSchambach** [comment]
The filtering options that omniboards provide are, despite being very useful for a quick visualization, very limit and easy to realize within the database directly. While yes, having a GUI interface is nice and super useful for data exploration, when the data becomes more complex and you are trying to visualize more complex structures within the data, getting familiar with either MongoDB or something like pandas is essential. 

However, as I said, I am in a similar situation and not completely familiar with MongoDB or the pymongo interface. However, I will be working on a toolbox for pymongo, probably in combination with pandas, making data aggregation more easy and quick. I will post it here, however, it may take a while since I have not yet found the time to do so.
