### ISSUE TITLE
Allow key-value pairs in config dictionary to be displayed in seperate column

### ISSUE THREAD

**Issue by BrEr** [vivekratnavel/omniboard#3]
My hyperparameters are stored in a dictionary. Currently omniboard does not support displaying nested values in a seperate column. So far example:

`"train" : {"batch_size":32,"epochs":100,"lr":0.01}`

It would be very nice to be able to display "batch_size " in it's own seperate column, opposed to the "train" column I have now.

**Comment by vivekratnavel** [comment]
@BrEr In this example, does it make sense to automatically expand `batch_size`, `epochs` and `lr`as separate columns and delete `train` column? Or do you want an option to expand each nested config as needed?

**Comment by u39kun** [comment]
Here are my thoughts on this.
We can treat nested objects by recursively parsing and add them as new columns.
Let's say we have something like the following:

`"train" : {"batch_size":32,"epochs":100,"lr":{"base_rate": 0.01, "drop_rate": 0.5, "epochs_per_drop": 10}}`

Then we can add columns with the following names:
* train.batch_size
* train.epochs
* train.lr.base_rate
* train.lr.drop_rate
* train.lr.epochs_per_drop

Also, this might be bigger in scope than how we handle nested objects, but my thoughts on this is that we should not be automatically adding all columns by default, because there could be tons of params; in such scenarios (and I think that is common), currently the user needs to select columns that don't need to be displayed and hide them, and then reorder the columns in particular order by doing drag-drop on the column headers.  I think it might be better if we don't add any columns but the user can choose which columns to be displayed and at the same time select the order of these columns (rather than doing it on the table column headers).  My two cents.  @vivekratnavel / @BrEr , what do you think?  (and this should probably be tracked separately).

**Comment by vivekratnavel** [comment]
@u39kun I agree with you. I will work on adding this feature.

**Comment by benjamin9555** [comment]
I have a nested dictionary of hyperparameters just like mentioned above, but in omniboard these columns are not displayed as discussed above. I'm using omniboard 2.12.0. Instead, it displays one column per top-level dictionary entry named `C training`, `C data` etc.
Here's my example dict:

```
{
'training':
    {'input_size_voxels': [108, 108, 108], 'output_size_voxels': [16, 16, 16]},
 'data':
    {'voxel_size': [5, 5, 5], 'num_classes': 2},
'model':
    {'num_fmaps': 32, 'fmap_inc_factor': 2, 'downsample_factors': [[2, 2, 2], [2, 2, 2], [2, 2, 2]]},
'seed': 575938453
}
```

**Comment by vivekratnavel** [comment]
@benjamin9555 By default Omniboard will list all first-level configs as separate columns. To display any nested dictionary as a column, you can add a [custom colum](https://vivekratnavel.github.io/omniboard/#/usage?id=custom-columns)

**Comment by benjamin9555** [comment]
Thanks for the hint, I had missed this.
Have you implemented automatically creating columns for nested dictionary configs and if so, how can I activate it? I would consider this a useful feature.

**Comment by vivekratnavel** [comment]
@benjamin9555 No, for a nested dictionary, you will have to use custom columns to display them in a separate column. It is only a one-time effort though and I don't plan to add automatic creation of columns for a nested dictionary as a new feature. But, I am open to accepting a pull request if someone is willing to implement the feature. Thanks!
