### ISSUE TITLE
Feature request: Keep opened run info open after page refresh

### ISSUE THREAD

**Issue by eukaryote31** [vivekratnavel/omniboard#68]

**Comment by vivekratnavel** [comment]
@eukaryote31 You can now use the "Reload" button in top right corner instead of page refresh and that will maintain the state of opened run info.

<img width="403" alt="Screen Shot 2019-03-16 at 11 51 33 PM" src="https://user-images.githubusercontent.com/1051198/54486523-a84c6400-4846-11e9-8160-c114863d775c.png">
